name: Purge jsDelivr cache and inject commit hash
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  mutate-and-purge:
    # Skip if the pusher is the bot or if we already marked the commit
    if: ${{ github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject short commit hash into main.js
        run: |
          set -euo pipefail
          COMMIT="${GITHUB_SHA::7}"
          echo "Injecting commit hash: ${COMMIT}"
          sed -i "s|__COMMIT_HASH__|${COMMIT}|" main.js || true

      - name: Commit and push updated main.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.js || true
          git commit -m "Inject commit hash [skip ci]" || exit 0
          git push origin HEAD:main

      - name: Purge & warm jsDelivr cache
        run: |
          set -euo pipefail
          NOW=$(date +%s)
          FILES=(
            "gh/bymschristensen/portfolio@main/main.js"
          )
          for F in "${FILES[@]}"; do
            echo "Purging  https://purge.jsdelivr.net/${F}"
            for i in {1..3}; do
              curl -fsSL "https://purge.jsdelivr.net/${F}" && break || sleep 1
            done
            echo "Warming  https://cdn.jsdelivr.net/${F}?build=${NOW}"
            curl -fsI "https://cdn.jsdelivr.net/${F}?build=${NOW}" >/dev/null || true
            echo "Warming  (map) https://cdn.jsdelivr.net/${F}.map?build=${NOW}"
            curl -fsI "https://cdn.jsdelivr.net/${F}.map?build=${NOW}" >/dev/null || true
          done
