name: Purge jsDelivr cache and inject commit hash
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject short commit hash into main.js
        shell: bash
        run: |
          set -euo pipefail
          COMMIT=$(git rev-parse --short HEAD)
          echo "Injecting commit hash: $COMMIT"
          # Replace placeholder in main.js
          sed -i "s|__COMMIT_HASH__|$COMMIT|" main.js

      - name: Commit and push updated main.js
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.js
          git commit -m "Inject commit hash [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

      - name: Purge & warm jsDelivr cache
        shell: bash
        run: |
          set -euo pipefail
          NOW=$(date +%s)
          FILES=(
            "gh/bymschristensen/portfolio@main/main.js"
            # Add more if needed:
            # "gh/bymschristensen/portfolio@main/main.css"
          )
          for F in "${FILES[@]}"; do
            echo "Purging  https://purge.jsdelivr.net/${F}"
            for i in {1..3}; do
              curl -fsSL "https://purge.jsdelivr.net/${F}" && break || sleep 1
            done
            echo "Warming  https://cdn.jsdelivr.net/${F}?build=${NOW}"
            curl -fsI "https://cdn.jsdelivr.net/${F}?build=${NOW}" >/dev/null || true
          done
          echo "Done."
