name: Purge jsDelivr cache
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge & warm jsDelivr for @main
        shell: bash
        run: |
          set -euo pipefail
          NOW=$(date +%s)
          FILES=(
            "gh/bymschristensen/portfolio@main/main.js"
            # "gh/bymschristensen/portfolio@main/main.css"
          )

          for F in "${FILES[@]}"; do
            echo "Purging  https://purge.jsdelivr.net/${F}"
            for i in {1..3}; do
              curl -fsSL "https://purge.jsdelivr.net/${F}" && break || sleep 1
            done
            echo "Warming  https://cdn.jsdelivr.net/${F}?build=${NOW}"
            curl -fsI "https://cdn.jsdelivr.net/${F}?build=${NOW}" >/dev/null || true
          done

          echo "Done."
